# docker compose run builder

services:
  br-builder:
    container_name: br-builder
#    user: <uid:gid>
    build:
      dockerfile: builder.Dockerfile
      context: .
    volumes:
      - .:/repo
